[package]
name = "snare"
version = "0.1.0"
authors = ["Laurence Tratt <laurie@tratt.net>"]
edition = "2018"

[dependencies]
getopts = "0.2"
hex = "0.4"
hmac = "0.7"
hyper = "0.13"
json = "0.12"
lettre = "0.9"
mio = "0.6"
nix = "0.16"
num_cpus = "1.12"
percent-encoding = "2.1"
sha-1 = "0.8"
tempfile = "3.1"
tokio = { version = "0.2", features = ["full"] }
whoami = "0.7"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
